### ISSUE TITLE
Quand choisir l'embouteilleur?

### ISSUE THREAD

**Issue by Portekoi** [lgi-wines/Gestion-Projet-CRM#10]
Une question simple mais à laquelle nous ne pouvons répondre sans votre aide : 

Quand doit-on faire choisir l'embouteilleur?

Suite à notre première entrevue en Mai dernier, il avait été évoqué le schéma suivant : 

`Choix du Client > Choix de l'embouteilleur > Ajout des produits dans l'offre commerciale`

Puis nous nous sommes revus sur Paris et le schéma a changé : 

`Choix du Client > Ajout des produits dans l'offre commerciale en choisissant l'embouteilleur`

C'est ce que j'ai mis en place dans la version que l'on développe : 

![image](https://user-images.githubusercontent.com/1560754/32368685-e1c90358-c086-11e7-87cc-c3d7ddd31e3d.png)

Pour moi, cela me semble normal de laisser toute la latitude aux commerciaux à ce niveau.

**Question : Une offre peut-elle effectivement concerner plusieurs embouteilleurs?**

**Comment by celinelgi** [comment]
Salut Damien,
Oui une offre commerciale peut concerner plusieurs embouteilleurs.
Je pense que nous devons laisser de la latitude aux commerciaux quant au choix de l'embouteilleur, et le conditionner en amont du produit risque d'être trop restrictif.
A ta disposition,

**Comment by Portekoi** [comment]
Merci beaucoup :)
