### ISSUE TITLE
Exemples pour la calculatrice de tarif

### ISSUE THREAD

**Issue by Portekoi** [lgi-wines/Gestion-Projet-CRM#21]
Je suis actuellement sur la calculatrice et l'affichage des prix dans le wizard de création.

Pouvez-vous compléter dans un nouvel onglet,  le fichier ci-dessous avec 2 vrais cas afin que je puisse reproduire les calculs rapidement?

Merci.

[LGI-Calculatrice-20180620D-1.xlsx](https://github.com/lgi-wines/Gestion-Projet-CRM/files/2119410/LGI-Calculatrice-20180620D-1.xlsx)

**Comment by lgazeau** [comment]
Céline va te prendre 2 exemples complets

**Comment by Portekoi** [comment]
Des nouvelles pour moi à ce sujet? Merci

**Comment by lgazeau** [comment]
Céline va te prendre 2 exemples complets
