### ISSUE TITLE
Bogues remontés au 27/08/2018

### ISSUE THREAD

**Issue by Portekoi** [lgi-wines/Gestion-Projet-CRM#25]
1. Marge Prestataire ne se calcule pas
2. Edulcoration n'est pas dans le prix "Sous total vin"
3. Renommer "Bouchon" en "Bouchage"
4. Recherche Habillage  + vin : limiter à N-2 max

**Comment by Portekoi** [comment]
1. Ok
2. Ok
3. Ok

J'ai aussi ajouté les agents. Ils sont bien pris en compte dans le calcul. J'ai juste un petit souci au niveau de v1 qui ne voit pas les agents ajoutés depuis v2. Je vais regarder demain avec le point 4 de cette liste.

**Comment by Portekoi** [comment]
Correction OK pour suppliers en doublon pour un composant.

**Comment by Portekoi** [comment]
Ok pour tous les points. Les agents remontent maintenant aussi dans v1.

**Comment by Portekoi** [comment]
V1 : 

![image](https://user-images.githubusercontent.com/1560754/45219798-609fbb00-b2ac-11e8-80ce-8af302a006fe.png)


V2 : 

![image](https://user-images.githubusercontent.com/1560754/45219769-51b90880-b2ac-11e8-8ff6-b6be7d036dc2.png)

J'ai les mêmes chiffres non?

**Comment by Portekoi** [comment]
Le "19" que tu saisies s'affiche à la ligne Marge Complémentaire et non MARGE BRUTE LGI ou alors j'ai râté un truc;

**Comment by lgazeau** [comment]
ERRATUM 
En faisant 3 choses à la fois, j'ai écrit des énormités.
En fait, c'est bon.
SORRY
