### ISSUE TITLE
OPIMIAN 2018 / Archivage et duplication des fiches produits

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Gestion-Projet-CRM#26]
Comme chaque année.

Client souche dans lequel se trouvent les 6 "Produits ACTIFS" **Opimian 2018** à dupliquer est THE OPIMIAN SOCIETY ClientID=88. 
Sur ce client, 6 PRODUITS sont activés avec **PV** et **Commissions AGENTS**.

**Etape 1** : Archivage de toutes les fiches actives des 9 clients suivants :
·        ClientID : 68
·        ClientID : 148
·        ClientID : 206
·        ClientID : 208
·        ClientID : 209
·        ClientID : 211
·        ClientID : 212
·        ClientID : 213 
·        ClientID : 214

**Etape 2** : Copies intégrales (avec PV et Commissions AGENTS) des 6 Produits "Actifs" du ClientID=88 dans les 9 autres clients.

Sont à copier intégralement les 6 ProductID suivants :
·        ProductID : 32542
·        ProductID : 32544
·        ProductID : 32546
·        ProductID : 32547
·        ProductID : 32548
·        ProductID : 32550

Dans les 9 ClientID suivants :
·        ClientID : 68
·        ClientID : 148
·        ClientID : 206
·        ClientID : 208
·        ClientID : 209
·        ClientID : 211
·        ClientID : 212
·        ClientID : 213
·        ClientID : 214

**Etape 3** : Enlever « Copie de » dans la désignation des produits

**Comment by Portekoi** [comment]
Je vais faire mon possible.

**Comment by Portekoi** [comment]
C'était pas une petite manip quand même... C'est bon je pense.

**Comment by lgazeau** [comment]
Ca n'a pas été si long finalement.
Je pense qu'effectivement c'est OK
MERCI

**Comment by Portekoi** [comment]
Je clos.
