### ISSUE TITLE
Réunion à Paris

### ISSUE THREAD

**Issue by MamboJoel** [lgi-wines/Gestion-Projet-CRM#3]
Pour la réunion à Paris je propose le mercredi 5 juillet. Est-ce que ça vous convient ?

**Comment by celinelgi** [comment]
Salut Nicolas,
Ok pour le 5 au matin car ensuite Cédric prend l'avion pour Bordeaux vers 13h. Est-ce que nous pourrons commencer le 4 en fin de journée vers 17h30 + diner? afin de prendre un peu d'avance sur le mercredi?
Merci,

**Comment by MamboJoel** [comment]
Je viens d'en discuter avec Damien ce serait plus simple alors de prendre la journée du 4.

**Comment by MamboJoel** [comment]
- Céline et Laurent arrive le 4 juillet à 9h.
- Cédric sera là le 5 juillet matin jusqu'à 11h.
