### ISSUE TITLE
REPORTING : Client Rename (Client ID 154 et 1337 deviennent 1337)

### ISSUE THREAD

**Issue by lgazeau** [lgi-wines/Gestion-Projet-CRM#30]
Salut Jacques,

Dans REPORTING

merci de fusionner les clients 4E FULLFILMENT COM LTD (Client ID : 154) 
et GIFTS DIRECT.COM (Client ID : 1337) 
sous GIFTS DIRECT.COM (Client ID : 1337) 

Table « ClientRename ».

Merci de me dire quand c’est OK.

**Comment by Portekoi** [comment]
Ca devrait être bon.

**Comment by lgazeau** [comment]
C'est OK 
MERCI
